import {
  Banknote,
  BarChart3,
  Boxes,
  Building2,
  ClipboardCheck,
  ClipboardList,
  FileInput,
  FolderTree,
  LayoutDashboard,
  LineChart,
  Package,
  PackageCheck,
  PieChart,
  Ruler,
  Settings,
  Shield,
  ShoppingCart,
  SlidersHorizontal,
  Store,
  Tags,
  Truck,
  Users,
  Warehouse,
} from "lucide-react";
import type { CommandAction, NavSection } from "~/shared/types";

/**
 * Full MVP navigation per docs/product/05-mvp-product-design-brief.md
 * Stitch supplies visual chrome only — this tree is the product IA.
 *
 * Multi-item sections collapse into one group icon in the icon rail.
 */
export const NAVIGATION_SECTIONS: NavSection[] = [
  {
    id: "overview",
    label: "Overview",
    icon: LayoutDashboard,
    items: [
      {
        id: "dashboard",
        label: "Dashboard",
        href: "/dashboard",
        icon: LayoutDashboard,
        permissions: ["dashboard:read"],
      },
      {
        id: "pos",
        label: "POS",
        href: "/pos",
        icon: ShoppingCart,
        permissions: ["sales:write"],
      },
    ],
  },
  {
    id: "catalog",
    label: "Catalog",
    icon: Package,
    items: [
      {
        id: "products",
        label: "Products",
        href: "/catalog",
        icon: Package,
        permissions: ["catalog:read"],
      },
      {
        id: "categories",
        label: "Categories",
        href: "/catalog/categories",
        icon: FolderTree,
        permissions: ["catalog:read"],
      },
      {
        id: "units",
        label: "Units",
        href: "/catalog/units",
        icon: Ruler,
        permissions: ["catalog:read"],
      },
      {
        id: "pricing",
        label: "Prices & Taxes",
        href: "/catalog/pricing",
        icon: Tags,
        permissions: ["catalog:read"],
      },
    ],
  },
  {
    id: "sales",
    label: "Sales",
    icon: ClipboardList,
    items: [
      {
        id: "sales-history",
        label: "Sales History",
        href: "/sales",
        icon: ClipboardList,
        permissions: ["sales:read"],
      },
    ],
  },
  {
    id: "inventory",
    label: "Inventory",
    icon: Warehouse,
    items: [
      {
        id: "stock",
        label: "Stock Availability",
        href: "/inventory",
        icon: Warehouse,
        permissions: ["inventory:read"],
      },
      {
        id: "purchases",
        label: "Purchases",
        href: "/purchasing",
        icon: FileInput,
        permissions: ["purchasing:read"],
      },
      {
        id: "receipts",
        label: "Goods Receipts",
        href: "/purchasing/receipts",
        icon: PackageCheck,
        permissions: ["purchasing:read"],
      },
      {
        id: "adjustments",
        label: "Adjustments",
        href: "/inventory/adjustments",
        icon: SlidersHorizontal,
        permissions: ["inventory:read"],
      },
      {
        id: "counts",
        label: "Stock Counts",
        href: "/inventory/counts",
        icon: ClipboardCheck,
        permissions: ["inventory:read"],
      },
      {
        id: "transfers",
        label: "Transfers",
        href: "/transfers",
        icon: Boxes,
        permissions: ["inventory:read"],
      },
      {
        id: "movements",
        label: "Movements",
        href: "/inventory/movements",
        icon: Truck,
        permissions: ["inventory:read"],
      },
    ],
  },
  {
    id: "reports",
    label: "Reports",
    icon: BarChart3,
    items: [
      {
        id: "reports-hub",
        label: "Overview",
        href: "/reports",
        icon: PieChart,
        permissions: ["reports:read"],
      },
      {
        id: "report-sales",
        label: "Sales",
        href: "/reports/sales",
        icon: LineChart,
        permissions: ["reports:sales"],
      },
      {
        id: "report-payments",
        label: "Payments",
        href: "/reports/payments",
        icon: Banknote,
        permissions: ["reports:payments"],
      },
      {
        id: "report-inventory",
        label: "Inventory",
        href: "/reports/inventory",
        icon: Boxes,
        permissions: ["reports:inventory"],
      },
    ],
  },
  {
    id: "settings",
    label: "Settings",
    icon: Settings,
    items: [
      {
        id: "organization",
        label: "Organization",
        href: "/settings",
        icon: Building2,
        permissions: ["settings:read"],
      },
      {
        id: "branches",
        label: "Branches",
        href: "/settings/branches",
        icon: Store,
        permissions: ["settings:read"],
      },
      {
        id: "users",
        label: "Users",
        href: "/settings/users",
        icon: Users,
        permissions: ["settings:read"],
      },
      {
        id: "roles",
        label: "Roles & Permissions",
        href: "/settings/roles",
        icon: Shield,
        permissions: ["settings:read"],
      },
    ],
  },
];

export const COMMAND_ACTIONS: CommandAction[] = [
  {
    id: "nav-dashboard",
    label: "Go to Dashboard",
    group: "Navigation",
    href: "/dashboard",
    icon: LayoutDashboard,
  },
  {
    id: "nav-pos",
    label: "Open POS",
    group: "Navigation",
    href: "/pos",
    icon: ShoppingCart,
  },
  {
    id: "nav-catalog",
    label: "Go to Products",
    group: "Navigation",
    href: "/catalog",
    icon: Package,
  },
  {
    id: "nav-sales",
    label: "Go to Sales History",
    group: "Navigation",
    href: "/sales",
    icon: ClipboardList,
  },
  {
    id: "nav-inventory",
    label: "Go to Stock Availability",
    group: "Navigation",
    href: "/inventory",
    icon: Warehouse,
  },
  {
    id: "nav-purchasing",
    label: "Go to Purchases",
    group: "Navigation",
    href: "/purchasing",
    icon: FileInput,
  },
  {
    id: "nav-reports",
    label: "Go to Sales Report",
    group: "Navigation",
    href: "/reports/sales",
    icon: LineChart,
  },
  {
    id: "nav-settings",
    label: "Go to Settings",
    group: "Navigation",
    href: "/settings",
    icon: Settings,
  },
  {
    id: "create-product",
    label: "Create product",
    description: "Open product drawer",
    group: "Actions",
    icon: Package,
    permissions: ["catalog:write"],
  },
  {
    id: "create-sale",
    label: "New sale",
    description: "Start a sale",
    group: "Actions",
    icon: ShoppingCart,
    permissions: ["sales:write"],
  },
  {
    id: "adjust-stock",
    label: "Adjust stock",
    description: "Record an inventory adjustment",
    group: "Actions",
    icon: Warehouse,
    permissions: ["inventory:write"],
  },
  {
    id: "create-purchase",
    label: "New purchase",
    description: "Create purchase order",
    group: "Actions",
    icon: FileInput,
    permissions: ["purchasing:write"],
  },
];
